// src/App.vue
<template>
  <div :class="classes.container">
    <Header />

    <div :class="classes.projects">
      <Project
          v-for="project in projects"
          :key="project.id"
          :project="project"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import Header from './components/Header.vue'
import Project from './components/Project.vue'
import { onMounted, ref } from 'vue'
import type { Project as ProjectType } from './types/project.ts'
import api from './api'

const projects = ref<ProjectType[]>([])
const fetchProjects = () => {
  return api.fetchProjects()
      .then((data) => {
        projects.value = data.projects
      }).catch((e) => {
        console.error(e)
      })
}
onMounted(() => {
  fetchProjects()
})
</script>

<style module="classes">
.container {
  max-width: 1280px;
  margin: 0 auto;
  padding: 32px;
}
.projects {}
</style>

// src/components/App/App.tsx
import styles from './App.module.css'
import Header from '../Header/Header.tsx'
import Project from '../Project/Project.tsx'
import { useEffect, useState } from "react"
import api from '../../api'
import type { Project as ProjectT } from '../../types/project.ts'

export default function App() {
    const [projects, setProjects] = useState<ProjectT[]>([])

    useEffect(() => {
        api.fetchProjects()
            .then((data) => {
                setProjects(data)
            })
    }, [])

    return (
        <div className={styles.app}>
            <Header />

            <main className={styles.main}>
                {projects.length > 0 && projects.map((project, index) => (
                    <Project key={index} project={project} />
                ))}
            </main>
        </div>
    )
}
